finger_1_controller:
  joints:
  - finger_1_segment_joint_1
  - finger_1_segment_joint_2
  - finger_1_segment_joint_3
  - finger_1_segment_joint_4
  - finger_1_segment_joint_5
  - finger_1_segment_joint_6
  - finger_1_segment_joint_7
  - finger_1_segment_joint_8
  - finger_1_segment_joint_9
  state_publisher_rate: 50
  type: segmented_controller/JointTrajectoryController
finger_2_controller:
  joints:
  - finger_2_segment_joint_1
  - finger_2_segment_joint_2
  - finger_2_segment_joint_3
  - finger_2_segment_joint_4
  - finger_2_segment_joint_5
  - finger_2_segment_joint_6
  - finger_2_segment_joint_7
  - finger_2_segment_joint_8
  - finger_2_segment_joint_9
  state_publisher_rate: 50
  type: segmented_controller/JointTrajectoryController
finger_3_controller:
  joints:
  - finger_3_segment_joint_1
  - finger_3_segment_joint_2
  - finger_3_segment_joint_3
  - finger_3_segment_joint_4
  - finger_3_segment_joint_5
  - finger_3_segment_joint_6
  - finger_3_segment_joint_7
  - finger_3_segment_joint_8
  - finger_3_segment_joint_9
  state_publisher_rate: 50
  type: segmented_controller/JointTrajectoryController
joint_state_controller:
  publish_rate: 50
  type: joint_state_controller/JointStateController
panda_arm_controller:
  constraints:
    panda_joint1:
      goal: 0
      trajectory: 0
    panda_joint2:
      goal: 0
      trajectory: 0
    panda_joint3:
      goal: 0
      trajectory: 0
    panda_joint4:
      goal: 0
      trajectory: 0
    panda_joint5:
      goal: 0
      trajectory: 0
    panda_joint6:
      goal: 0
      trajectory: 0
    panda_joint7:
      goal: 0
      trajectory: 0
    stopped_velocity_tolerance: 0
  joints:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
  state_publish_rate: 50
  type: position_controllers/JointTrajectoryController
panda_hand_controller:
  constraints:
    finger_1_prismatic_joint:
      goal: 0
      trajectory: 0
    finger_1_revolute_joint:
      goal: 0
      trajectory: 0
    finger_2_prismatic_joint:
      goal: 0
      trajectory: 0
    finger_2_revolute_joint:
      goal: 0
      trajectory: 0
    finger_3_prismatic_joint:
      goal: 0
      trajectory: 0
    finger_3_revolute_joint:
      goal: 0
      trajectory: 0
    palm_prismatic_joint:
      goal: 0
      trajectory: 0
    stopped_velocity_tolerance: 0
  joints:
  - finger_1_prismatic_joint
  - finger_1_revolute_joint
  - finger_2_prismatic_joint
  - finger_2_revolute_joint
  - finger_3_prismatic_joint
  - finger_3_revolute_joint
  - palm_prismatic_joint
  state_publish_rate: 50
  type: position_controllers/JointTrajectoryController
