gripper_config:
  effort_control: false
  is_segmented: true
  num_segments: 10
  previous_update:
    effort_control: false
    old_is_segmented: true
    old_num_segments: 10
    torsion: false
  torsion: false
