<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="segmented_finger" params="prefix num_segments torsion">
  
  	<!-- PARAMETERS TO BE SET BY HAND -->

    <!-- User defined variables -->
    <xacro:property name="finger_length_mm" value="190.0"/>
    <xacro:property name="hook_length_mm" value="35.0"/>
    <xacro:property name="finger_width_mm" value="28.0"/>
    <xacro:property name="finger_thickness_mm" value="0.9"/>
    <xacro:property name="hook_angle_d" value="90.0"/>
    <xacro:property name="finger_mass_g" value="75.0"/>

    <!-- macros to set the sdf elements, all here together for convienience -->
    <!-- Tags for gazebo, see: http://gazebosim.org/tutorials?tut=ros_urdf -->
    <xacro:macro name="link_properties">
        <material>Gazebo/Orange</material>
        <mu1>0.1</mu1>
        <mu2>0.1</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.001</minDepth>
        <!-- <kp>100</kp>
        <kd>1</kd> -->
    </xacro:macro>
    <xacro:macro name="joint_properties">
      <provideFeedback>1</provideFeedback>
      <springReference>0.0</springReference>
      <implicitSpringDamper>1</implicitSpringDamper>
    </xacro:macro>
    <xacro:macro name="bending_stiffness">
      <springStiffness>3.0</springStiffness>
    </xacro:macro>
    <xacro:macro name="torsional_stiffness">
      <springStiffness>10.0</springStiffness>
    </xacro:macro>

    <!-- these are implemented in the <dynamics> tags in each joint -->
    <xacro:property name="joint_friction" value="0.0"/>
    <xacro:property name="joint_damping" value="0.01"/>
    
    <!-- END OF PARAMETERS TO BE SET BY HAND -->

    <!-- Automatially calculated variables -->
    <xacro:property name="finger_length" value="${finger_length_mm * 0.001}"/>
    <xacro:property name="segment_length" value="${(finger_length_mm / num_segments) * 0.001}"/>
    <xacro:property name="segment_width" value="${finger_width_mm * 0.001}"/>
    <xacro:property name="segment_thickness" value="${finger_thickness_mm * 0.001}"/>
    <xacro:property name="hook_length" value="${hook_length_mm * 0.001}"/>
    <xacro:property name="hook_angle" value="${(hook_angle_d / 180.0) * 3.1415926535897}"/>

    <!-- find inertia of each segment -->
    <xacro:property name="finger_mass" value="${finger_mass_g * 0.001}"/>
    <xacro:property name="segment_mass" 
      value="${(finger_mass * segment_length) / (finger_length + hook_length)}"/>
    <!-- x axis along finger length, no axis displacement-->
    <xacro:property name="segment_ixx"
      value="${(1.0/12.0) * segment_mass * (segment_thickness ** 2 + segment_width ** 2)}"/>
    <!-- y axis is joint axis, has axis displacment from centre of mass -->
    <xacro:property name="segment_iyy"
      value="${(1.0/12.0) * segment_mass * (segment_length ** 2 + segment_thickness ** 2)
              + segment_mass * (segment_length / 2.0) ** 2}"/>
    <!-- z axis is out of the segment, has axis displacement-->
    <xacro:property name="segment_izz"
      value="${(1.0/12.0) * segment_mass * (segment_length ** 2 + segment_width ** 2)
              + segment_mass * (segment_length / 2.0) ** 2}"/>

    <xacro:property name="stability_factor" value="1"/>

    <!-- Simplistic inertia macro for Gazebo -->
    <xacro:macro name="segment_inertial" params="mass num">
      <inertial>
        <mass value="${segment_mass}"/>
        <inertia ixx="${segment_ixx * stability_factor}"
                 iyy="${segment_iyy * stability_factor}"
                 izz="${segment_izz * stability_factor}"
                ixy="0.00" iyz="0.00" ixz="0.00" />
        <!-- <inertia ixx="${1e-6 * stability_factor}"
                 iyy="${1e-6 * stability_factor}"
                 izz="${1e-6 * stability_factor}"
                ixy="0.00" iyz="0.00" ixz="0.00" /> -->
      </inertial>
    </xacro:macro>

    <!-- Macro to add a segment link -->
    <xacro:macro name="add_segment_link" params="number">
      <link name="${prefix}_segment_link_${number}">
        <xacro:segment_inertial mass="${(75 * 0.001) / num_segments}" num="${number}"/>
        <visual>
          <origin xyz="${segment_length / 2} 0 0"
                  rpy="0 0 0"/>
          <geometry>
            <box size="${segment_length} ${segment_width} ${segment_thickness}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${segment_length / 2} 0 0"
                rpy="0 0 0"/>
          <geometry>
            <box size="${segment_length} ${segment_width} ${segment_thickness}"/>
          </geometry>
        </collision>
      </link>
      <gazebo reference="${prefix}_segment_link_${number}">
        <xacro:link_properties/>
      </gazebo>
    </xacro:macro>

    <!-- Macro to add a segment joint -->
    <xacro:macro name="add_segment_joint" params="number">
      <!-- if torsion=true, every other joint is torisonal, else all are bending-->
      <xacro:if value="${(number % 2 * torsion) + (1 - torsion)}">
        <!-- bending joint -->
        <joint name="${prefix}_segment_joint_${number - 1}" type="revolute">
          <axis xyz="0 1 0" rpy="0 0 0"/>
          <parent link="${prefix}_segment_link_${number - 1}"/>
          <child link="${prefix}_segment_link_${number}"/>
          <origin xyz="${segment_length} 0 0"
                  rpy="0 0 0"/>
          <limit effort="1000.0"
                lower="-1.0"
                upper="1.0"
                velocity="1.0"/>
          <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
        </joint>
        <gazebo reference="${prefix}_segment_joint_${number - 1}">
          <xacro:joint_properties/>
          <xacro:bending_stiffness/>
        </gazebo>
      </xacro:if>
      <!-- only use torsional joints if torsion=true -->
      <xacro:if value="${((number - 1) % 2) * torsion}">
        <!-- torsional joint -->
        <joint name="${prefix}_segment_joint_${number - 1}" type="revolute">
          <axis xyz="1 0 0" rpy="0 0 0"/>
          <parent link="${prefix}_segment_link_${number - 1}"/>
          <child link="${prefix}_segment_link_${number}"/>
          <origin xyz="${segment_length} 0 0"
                  rpy="0 0 0"/>
          <limit effort="1000.0"
                lower="-1.0"
                upper="1.0"
                velocity="1.0"/>
          <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
        </joint>
        <gazebo reference="${prefix}_segment_joint_${number - 1}">
          <xacro:joint_properties/>
          <xacro:torsional_stiffness/>
        </gazebo>
      </xacro:if>
      <!-- set transmission for gazebo ROS controllers-->
      <transmission name="${prefix}_segment_tran_${number - 1}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_segment_joint_${number - 1}">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_segment_motor_${number - 1}">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:macro>

    <!-- Create the base link -->
    <xacro:add_segment_link number="1"/>

    <!-- Loop through each segment-->
    <xacro:macro name="loop" params="iterations">

      <!-- make the next segment -->
      <xacro:add_segment_link number="${num_segments - iterations}"/>

      <!-- make a joint to connect the segments -->
      <xacro:add_segment_joint number="${num_segments - iterations}"/>

      <!-- Recursively call the loop macro until iterations = 0 -->
      <xacro:if value="${iterations}">
        <xacro:loop iterations="${iterations - 1}"/>
      </xacro:if>
    </xacro:macro>

    <!-- Execute the loop macro -->
    <xacro:loop iterations="${num_segments - 2}"/>

    <!-- Add the finger hook link -->
    <link name="${prefix}_finger_hook_link">
      <xacro:segment_inertial mass="${(75 * 0.001) / num_segments}" num="${num_segments}"/>
      <visual>
        <origin xyz="${hook_length / 2} 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="${hook_length} ${segment_width} ${segment_thickness}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${hook_length / 2} 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="${hook_length} ${segment_width} ${segment_thickness}"/>
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}_finger_hook_link">
      <xacro:link_properties/>
    </gazebo>

    <!-- Connect the finger hook via a fixed joint -->
    <joint name="${prefix}_finger_hook_joint" type="fixed">
      <parent link="${prefix}_segment_link_${num_segments}"/>
      <child link="${prefix}_finger_hook_link"/>
      <origin xyz="${segment_length} 0 0"
              rpy="0 ${-hook_angle} 0"/>
    </joint>

  </xacro:macro>

  <!-- macro to create groups -->
  <xacro:macro name="build_group" params="prefix i">
    <xacro:property name="imax" value="${i}"/>
    <group name="${prefix}_group">
      <xacro:macro name="loop_group" params="prefix i">
        <link name="${prefix}_segment_link_${imax - i}"/>
        <xacro:if value="${i}">
          <xacro:loop_group i="${i - 1}" prefix="${prefix}"/>
        </xacro:if>
      </xacro:macro>
      <xacro:loop_group prefix="${prefix}" i="${imax - 1}"/>
      <link name="${prefix}_finger_hook_link"/>
    </group>
  </xacro:macro>

  <!-- macro to disable collisions-->
  <xacro:macro name="disable_finger_collisions" params="prefix imax">

    <!-- macro to disable all collisions for a link -->
    <xacro:macro name="disable_all" params="j link_name">

      <!-- create a macro to loop through the links -->
      <xacro:macro name="loop_disable" params="k">
        <xacro:if value="${k}">
          <disable_collisions link1="${link_name}"
                              link2="${prefix}_segment_link_${k}"
                              reason="Adjacent"/>
          <xacro:loop_disable k="${k - 1}"/>
        </xacro:if>
      </xacro:macro>

      <!-- disable wrt to the start and end -->
      <disable_collisions link1="${link_name}"
                          link2="${prefix}"
                          reason="Adjacent"/>
      <disable_collisions link1="${link_name}"
                          link2="${prefix}_finger_hook_link"
                          reason="Adjacent"/>

      <!-- loop through all links backwards in the chain to disable them -->
      <xacro:loop_disable k="${j - 1}"/>
    </xacro:macro>

    <!-- now we need a macro to loop through each link in the chain -->
    <xacro:macro name="loop_chain" params="i">
      <xacro:if value="${i}">
        <!-- disable all collisions at this link, then loop to next one-->
        <xacro:disable_all j="${i}" 
                           link_name="${prefix}_segment_link_${i}"/>
        <xacro:loop_chain i="${i - 1}"/>
      </xacro:if>
    </xacro:macro>

    <!-- disable collisions between hook and base -->
    <disable_collisions link1="${prefix}"
                        link2="${prefix}_finger_hook_link"
                        reason="Adjacent"/>

    <!-- execute the top level macro to loop through entire chain -->
    <xacro:loop_chain i="${imax}"/>

  </xacro:macro>

  <!-- macro to include gazebo plugins -->
  <xacro:macro name="gazebo_plugin">
    <gazebo>
      <plugin name="finger_controller_plugin" filename="libfinger_controller_plugin.so"/>
    </gazebo>
  </xacro:macro>
    
</robot>
