controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

  - name: panda_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - finger_1_prismatic_joint
        - finger_1_revolute_joint
        - finger_2_prismatic_joint
        - finger_2_revolute_joint
        - finger_3_prismatic_joint
        - finger_3_revolute_joint
        - palm_prismatic_joint
        
  - name: joint_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
        
  - name: finger_controller
    action_ns: follow_joint_trajectory
    default: true
    joint_names:
        - finger_1_segment_joint_1
        - finger_2_segment_joint_1
        - finger_3_segment_joint_1
        - finger_1_segment_joint_2
        - finger_2_segment_joint_2
        - finger_3_segment_joint_2
        - finger_1_segment_joint_3
        - finger_2_segment_joint_3
        - finger_3_segment_joint_3
        - finger_1_segment_joint_4
        - finger_2_segment_joint_4
        - finger_3_segment_joint_4
        - finger_1_segment_joint_5
        - finger_2_segment_joint_5
        - finger_3_segment_joint_5
        - finger_1_segment_joint_6
        - finger_2_segment_joint_6
        - finger_3_segment_joint_6
        - finger_1_segment_joint_7
        - finger_2_segment_joint_7
        - finger_3_segment_joint_7
        - finger_1_segment_joint_8
        - finger_2_segment_joint_8
        - finger_3_segment_joint_8
        - finger_1_segment_joint_9
        - finger_2_segment_joint_9
        - finger_3_segment_joint_9
        
        
        
