controller_list:
- action_ns: follow_joint_trajectory
  default: true
  joints:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
  name: panda_arm_controller
  type: FollowJointTrajectory
- action_ns: follow_joint_trajectory
  default: true
  joints:
  - finger_1_prismatic_joint
  - finger_1_revolute_joint
  - finger_2_prismatic_joint
  - finger_2_revolute_joint
  - finger_3_prismatic_joint
  - finger_3_revolute_joint
  - palm_prismatic_joint
  name: panda_hand_controller
  type: FollowJointTrajectory
- action_ns: follow_joint_trajectory
  joint_names:
  - finger_1_segment_joint_1
  - finger_1_segment_joint_2
  - finger_1_segment_joint_3
  - finger_1_segment_joint_4
  - finger_1_segment_joint_5
  - finger_1_segment_joint_6
  - finger_1_segment_joint_7
  - finger_1_segment_joint_8
  - finger_1_segment_joint_9
  name: finger_1_controller
  type: FollowJointTrajectory
- action_ns: follow_joint_trajectory
  joint_names:
  - finger_2_segment_joint_1
  - finger_2_segment_joint_2
  - finger_2_segment_joint_3
  - finger_2_segment_joint_4
  - finger_2_segment_joint_5
  - finger_2_segment_joint_6
  - finger_2_segment_joint_7
  - finger_2_segment_joint_8
  - finger_2_segment_joint_9
  name: finger_2_controller
  type: FollowJointTrajectory
- action_ns: follow_joint_trajectory
  joint_names:
  - finger_3_segment_joint_1
  - finger_3_segment_joint_2
  - finger_3_segment_joint_3
  - finger_3_segment_joint_4
  - finger_3_segment_joint_5
  - finger_3_segment_joint_6
  - finger_3_segment_joint_7
  - finger_3_segment_joint_8
  - finger_3_segment_joint_9
  name: finger_3_controller
  type: FollowJointTrajectory
