controller_list:
  - name: fake_panda_arm_controller
    joints:
    	- panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_panda_hand_controller
    joints:
      - finger_1_prismatic_joint
      - finger_1_revolute_joint
      - finger_2_prismatic_joint
      - finger_2_revolute_joint
      - finger_3_prismatic_joint
      - finger_3_revolute_joint
      - palm_prismatic_joint
initial:  # Define initial robot poses.
  - group: panda_arm
    pose: ready_pose
  - group: gripper
    pose: ready_pose
