# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: panda_arm
  joint_model_group_pose: ready_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - finger_1_prismatic_joint
    - finger_1_revolute_joint
    - finger_2_prismatic_joint
    - finger_2_revolute_joint
    - finger_3_prismatic_joint
    - finger_3_revolute_joint
    - palm_prismatic_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: gripper_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - finger_1_prismatic_joint
      - finger_1_revolute_joint
      - finger_2_prismatic_joint
      - finger_2_revolute_joint
      - finger_3_prismatic_joint
      - finger_3_revolute_joint
      - palm_prismatic_joint
arm_position_controller:
#  type: position_controllers/JointPositionController
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_position_controller:
#  type: position_controllers/JointPositionController
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_1_prismatic_joint
    - finger_1_revolute_joint
    - finger_2_prismatic_joint
    - finger_2_revolute_joint
    - finger_3_prismatic_joint
    - finger_3_revolute_joint
    - palm_prismatic_joint
  gains:
    finger_1_prismatic_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_1_revolute_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_2_prismatic_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_2_revolute_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_3_prismatic_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_3_revolute_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_prismatic_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
