<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="segmented_finger" params="prefix num_segments">

    <!-- User defined variables -->
    <!-- <xacro:property name="num_segments" value="10"/> -->
    <xacro:property name="finger_length_mm" value="190.0"/>
    <xacro:property name="hook_length_mm" value="35.0"/>
    <xacro:property name="finger_width_mm" value="28.0"/>
    <xacro:property name="finger_thickness_mm" value="0.9"/>
    <xacro:property name="hook_angle_d" value="90.0"/>
    <xacro:property name="bending_stiffness" value="100.0"/>
    <xacro:property name="torsional_stiffness" value="1000.0"/>
    <xacro:property name="bending_damping" value="0.1"/>
    <xacro:property name="torsional_damping" value="0.1"/>

    <!-- Automatially calculated variables -->
    <xacro:property name="segment_length" value="${(finger_length_mm / num_segments) * 0.001}"/>
    <xacro:property name="segment_width" value="${finger_width_mm * 0.001}"/>
    <xacro:property name="segment_thickness" value="${finger_thickness_mm * 0.001}"/>
    <xacro:property name="hook_length" value="${hook_length_mm * 0.001}"/>
    <xacro:property name="hook_angle" value="${(hook_angle_d / 180.0) * 3.1415926535897}"/>
    <xacro:property name="segment_number" value="0"/>

    <!-- Simplistic inertia macro for Gazebo -->
    <xacro:macro name="segment_inertial" params="mass">
      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="1e-3" iyy="1e-3" izz="1e-3"
                ixy="0.00" iyz="0.00" ixz="0.00" />
      </inertial>
    </xacro:macro>

    <!-- Macro to add a segment link -->
    <xacro:macro name="add_segment_link" params="number">
      <link name="${prefix}_segment_link_${number}">
        <xacro:segment_inertial mass="${(75 * 0.001) / num_segments}"/>
        <visual>
          <origin xyz="${segment_length / 2} 0 0"
                  rpy="0 0 0"/>
          <geometry>
            <box size="${segment_length} ${segment_width} ${segment_thickness}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="${segment_length / 2} 0 0"
                rpy="0 0 0"/>
          <geometry>
            <box size="${segment_length} ${segment_width} ${segment_thickness}"/>
          </geometry>
        </collision>
        <gazebo reference="${prefix}_segment_link_${number}">
          <material>Gazebo/White</material>
          <mu1>100</mu1>
          <mu2>100</mu2>
          <kp>100</kp>
          <kd>1</kd>
        </gazebo>
      </link>
    </xacro:macro>

    <!-- Macro to add a segment joint -->
    <xacro:macro name="add_segment_joint" params="number">
      <joint name="${prefix}_segment_joint_${number - 1}" type="revolute">
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <parent link="${prefix}_segment_link_${number - 1}"/>
        <child link="${prefix}_segment_link_${number}"/>
        <origin xyz="${segment_length} 0 0"
                rpy="0 0 0"/>
        <limit effort="1000.0"
               lower="-1.0"
               upper="1.0"
               velocity="1.0"/>
        <dynamics damping="${bending_damping}"/>
        <gazebo reference="${prefix}_segment_joint_${number - 1}">
          <spring_reference>0.0</spring_reference>
          <!-- note series springs have reduced stiffness 10+10+10 = 10/3 -->
          <spring_stiffness>1000000.0</spring_stiffness>
          <implicitSpringDamper>1</implicitSpringDamper>
          <!-- <stopCfm>0.1</stopCfm>
          <stopErp>0.1</stopErp>
          <dampingFactor>0.1</dampingFactor> -->
        </gazebo>
      </joint>
      <transmission name="${prefix}_segment_tran_${number - 1}">
          <type>transmission_interface/SimpleTransmission</type>
          <joint name="${prefix}_segment_joint_${number - 1}">

                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>

          </joint>
          <actuator name="${prefix}_segment_motor_${number - 1}">

                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>

              <!-- <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface> -->
              <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
              <mechanicalReduction>1</mechanicalReduction>
          </actuator>
        </transmission>
    </xacro:macro>

    <!-- Create the base link -->
    <xacro:add_segment_link number="1"/>

    <!-- Loop through each segment-->
    <xacro:macro name="loop" params="iterations">

      <!-- make the next segment -->
      <xacro:add_segment_link number="${num_segments - iterations}"/>

      <!-- make a joint to connect the segments -->
      <xacro:add_segment_joint number="${num_segments - iterations}"/>

      <!-- Recursively call the loop macro until iterations = 0 -->
      <xacro:if value="${iterations}">
        <xacro:loop iterations="${iterations - 1}"/>
      </xacro:if>
    </xacro:macro>

    <!-- Execute the loop macro -->
    <xacro:loop iterations="${num_segments - 2}"/>

    <!-- Add the finger hook link -->
    <link name="${prefix}_finger_hook_link">
      <xacro:segment_inertial mass="${(75 * 0.001) / num_segments}"/>
      <visual>
        <origin xyz="${hook_length / 2} 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="${hook_length} ${segment_width} ${segment_thickness}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${hook_length / 2} 0 0"
                rpy="0 0 0"/>
        <geometry>
          <box size="${hook_length} ${segment_width} ${segment_thickness}"/>
        </geometry>
      </collision>
    </link>

    <!-- Connect the finger hook via a fixed joint -->
    <joint name="${prefix}_finger_hook_joint" type="fixed">
      <parent link="${prefix}_segment_link_${num_segments}"/>
      <child link="${prefix}_finger_hook_link"/>
      <origin xyz="${segment_length} 0 0"
              rpy="0 ${-hook_angle} 0"/>
    </joint>

    <!-- disable collisions between link and hook -->
    <disable_collisions link1="${prefix}_segment_link_${num_segments}"
                        link2="${prefix}_finger_hook_link"
                        reason="Adjacent"/>

  </xacro:macro>

  <!-- macro to create groups -->
  <xacro:macro name="build_group" params="prefix i">
    <xacro:property name="imax" value="${i}"/>
    <group name="${prefix}_group">
      <xacro:macro name="loop_group" params="prefix i">
        <link name="${prefix}_segment_link_${imax - i}"/>
        <xacro:if value="${i}">
          <xacro:loop_group i="${i - 1}" prefix="${prefix}"/>
        </xacro:if>
      </xacro:macro>
      <xacro:loop_group prefix="${prefix}" i="${imax - 1}"/>
      <link name="${prefix}_finger_hook_link"/>
    </group>
  </xacro:macro>

  <!-- macro to disable collisions-->
  <xacro:macro name="disable_finger_collisions" params="prefix imax">

    <!-- macro to disable all collisions for a link -->
    <xacro:macro name="disable_all" params="j link_name">

      <!-- create a macro to loop through the links -->
      <xacro:macro name="loop_disable" params="k">
        <xacro:if value="${k}">
          <disable_collisions link1="${link_name}"
                              link2="${prefix}_segment_link_${k}"
                              reason="Adjacent"/>
          <xacro:loop_disable k="${k - 1}"/>
        </xacro:if>
      </xacro:macro>

      <!-- disable wrt to the start and end -->
      <disable_collisions link1="${link_name}"
                          link2="${prefix}"
                          reason="Adjacent"/>
      <disable_collisions link1="${link_name}"
                          link2="${prefix}_finger_hook_link"
                          reason="Adjacent"/>

      <!-- loop through all links backwards in the chain to disable them -->
      <xacro:loop_disable k="${j - 1}"/>
    </xacro:macro>

    <!-- now we need a macro to loop through each link in the chain -->
    <xacro:macro name="loop_chain" params="i">
      <xacro:if value="${i}">
        <!-- disable all collisions at this link, then loop to next one-->
        <xacro:disable_all j="${i}" 
                           link_name="${prefix}_segment_link_${i}"/>
        <xacro:loop_chain i="${i - 1}"/>
      </xacro:if>
    </xacro:macro>

    <!-- disable collisions between hook and base -->
    <disable_collisions link1="${prefix}"
                        link2="${prefix}_finger_hook_link"
                        reason="Adjacent"/>

    <!-- execute the top level macro to loop through entire chain -->
    <xacro:loop_chain i="${imax}"/>

  </xacro:macro>
    
</robot>
